name: "🪲 Bug report"
description: Report an issue that should be fixed.
title: "bug: <symptom> when <condition>"
labels:
  - bug
  - needs triage
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report.

        Before filing, make sure you are testing against the latest `main`.
        Please include exact commands and raw output where possible.

  - type: input
    id: version
    attributes:
      label: Skill version/ref
      description: Branch, commit SHA, or release tag.
      placeholder: main@<sha>

  - type: input
    id: platform
    attributes:
      label: Platform
      description: OS and shell; include output of `uname -mprs` when available.
      placeholder: Darwin arm64 ... / zsh

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One paragraph with expected vs actual behavior.
      placeholder: |
        Expected:
        Actual:
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Ordered, copy-pasteable commands.
      placeholder: |
        1. cd /path/to/repo
        2. export FOO=bar
        3. ./scripts/...
    validations:
      required: true

  - type: textarea
    id: minimal_command
    attributes:
      label: Minimal failing command or snippet
      description: Smallest single command that still fails.
      render: shell
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Logs / evidence
      description: Include exact output, stack traces, CI links, or screenshots.
      render: shell
    validations:
      required: true

  - type: input
    id: related_tooling
    attributes:
      label: Related tool versions (optional)
      description: Codex/Claude/GitHub CLI versions if relevant.
      placeholder: codex --version, gh --version, claude --version

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I verified this is reproducible on the latest `main`.
          required: true
        - label: I searched existing issues and did not find a duplicate.
          required: true
